name: Deploy GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./  # Root directory since no build is required

      # Step 3: Notify Slack of successful deployment
      - name: Notify Slack of successful deployment
        if: success()  # This runs only if the deployment was successful
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data '{"text":"Static website has been deployed to GitHub Pages successfully!"}' \
          ${{ secrets.SLACK_WEBHOOK_URL }}

      # Step 4: Notify Slack of deployment failure
      - name: Notify Slack of deployment failure
        if: failure()  # This runs only if the deployment fails
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data '{"text":"Static website deployment to GitHub Pages failed!"}' \
          ${{ secrets.SLACK_WEBHOOK_URL }}
